modLoader="javafml"
loaderVersion="[28,)"
license="MIT"
issueTrackerURL="https://github.com/fgsoftware1/fgmod/issues"

[[mods]]
modId="fgmod"
version="${file.jarVersion}"
displayName="Fgmod"
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="fgmod-forge.png" #optional
credits="Gabriel Aguiar and github contributors"
authors="Gabriel Aguiar and github contributors"
description='''

'''
[[dependencies.fgmod]]
   modId="forge"
   mandatory=true
   versionRange="[28,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fgmod]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.4,1.15)"
   ordering="NONE"
   side="BOTH"
